name: Publish Nightly Build (1.21.1)
 
on:
  push:
    branches: ["dev/**"]
env:
  TEST_RELEASE_NUM: ${{ vars.TEST_RELEASE_NUM }}
  JAVA_VERSION: 21
  MC_VER: 1.21.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print release num
        run: "echo Release num: ${{ env.TEST_RELEASE_NUM }}"

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          allowUpdates: true
          draft: true
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.github_release.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
