name: Publish Nightly Build (1.21.1)
 
on:
  push:
    branches: ["dev/**"]
env:
  TEST_RELEASE_NUM: ${{ vars.TEST_RELEASE_NUM }}
  JAVA_VERSION: 21
  MC_VER: 1.21.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the changelog
        run: |
          cat << "EOF"
          ${{ steps.changelog.outputs.changelog }}
          EOF

      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          allowUpdates: true
          draft: true
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
#